# Stock Price Time Series
TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY'
TIME_SERIES_DAILY = 'TIME_SERIES_DAILY'
TIME_SERIES_DAILY_ADJUSTED = 'TIME_SERIES_DAILY_ADJUSTED'
TIME_SERIES_WEEKLY = 'TIME_SERIES_WEEKLY'
TIME_SERIES_WEEKLY_ADJUSTED = 'TIME_SERIES_WEEKLY_ADJUSTED'
TIME_SERIES_MONTHLY = 'TIME_SERIES_MONTHLY'
TIME_SERIES_MONTHLY_ADJUSTED = 'TIME_SERIES_MONTHLY_ADJUSTED'

# Fundamental Data
BALANCE_SHEET = 'BALANCE_SHEET'
INCOME_STATEMENT = 'INCOME_STATEMENT'
CASH_FLOW = 'CASH_FLOW'
EARNINGS = 'EARNINGS'
OVERVIEW = 'OVERVIEW'  # Summary of key metrics

# Sector Performance
SECTOR = 'SECTOR'

# Forex & Crypto (optional for your use case)
FX_DAILY = 'FX_DAILY'
CRYPTO_INTRADAY = 'CRYPTO_INTRADAY'

# Technical Indicators (if using analytics like RSI, SMA, etc.)
SMA = 'SMA'
EMA = 'EMA'
RSI = 'RSI'
MACD = 'MACD'
ADX = 'ADX'
BBANDS = 'BBANDS'
STOCH = 'STOCH'

# Market News & Sentiment
NEWS_SENTIMENT = 'NEWS_SENTIMENT'

# Global Quote (current snapshot)
GLOBAL_QUOTE = 'GLOBAL_QUOTE'